version: '3'
services:
  app:
    build: ../app
    volumes:
        - /var/run/docker.sock/:/var/run/docker.sock
        - ../app/log:/app/log
    ports:
        - 8080:8000
    links:
        - db:db
    depends_on:
        - db
        - gesis_rec_precom
        - gesis_rec_pyserini
        - gesis_rec_pyterrier
        - livivo_base
        - lemuren_elk
        - tekmas
        - save_fami
    environment:
        - RANKSYS_LIST=livivo_base
        - RANKSYS_PRECOM_LIST=lemuren_elk tekmas save_fami
        - RANKSYS_BASE=livivo_base
        - RECSYS_LIST=gesis_rec_pyserini gesis_rec_pyterrier
        - RECSYS_PRECOM_LIST=gesis_rec_precom
        - RECSYS_BASE=gesis_rec_pyserini
        - STELLA_SERVER_ADDRESS=https://lilas.stella-project.org
        - STELLA_SERVER_USER=gesis@stella-project.org
        - STELLA_SERVER_PASS=pass
        - STELLA_SERVER_USERNAME=GESIS
        - INTERLEAVE=True
        - BULK_INDEX=True
        - DELETE_SENT_SESSION=True
        - INTERVAL_DB_CHECK=3
        - SESSION_EXPIRATION=6
  db:
    image: postgres
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
  gesis_rec_precom:
    build: https://github.com/stella-project/gesis_rec_precom.git#master
    container_name: gesis_rec_precom
    volumes:
        - ../data/:/data/
        - ../index/gesis_rec_precom:/index/
  gesis_rec_pyserini:
    build: https://github.com/stella-project/gesis_rec_pyserini.git#master
    container_name: gesis_rec_pyserini
    volumes:
        - ../data/:/data/
        - ../index/gesis_rec_pyserini:/index/
  gesis_rec_pyterrier:
    build: https://github.com/stella-project/gesis_rec_pyterrier.git#master
    container_name: gesis_rec_pyterrier
    volumes:
        - ../data/:/data/
        - ../index/gesis_rec_pyterrier:/index/
  livivo_base:
    build: https://github.com/stella-project/livivo_rank_base.git#main
    container_name: livivo_base
    volumes:
        - ../data/:/data/
        - ../index/livivo_base:/index/
  lemuren_elk:
    build: https://github.com/stella-project/lemuren_elk_precom.git#main
    container_name: lemuren_elk
    volumes:
        - ../data/:/data/
        - ../index/lemuren_elk:/index/
  tekmas:
    build: https://github.com/stella-project/tekmas_precom.git#main
    container_name: tekmas
    volumes:
        - ../data/:/data/
        - ../index/tekmas:/index/
  save_fami:
    build: https://github.com/stella-project/save_fami_precom.git#main
    container_name: save_fami
    volumes:
        - ../data/:/data/
        - ../index/save_fami:/index/
