#!/usr/bin/env python2.7

from subprocess import Popen, PIPE
import json
import os
import sys

query = sys.argv[1]

CMD = "java -jar /lucene/LuceneRanker.jar search " + query

p = Popen(CMD.split(), stdout=PIPE, stderr=PIPE)
output, err = p.communicate()
rc = p.returncode

l = []

splitted = output.split('\n')

for entry in splitted[1:-1]:
    l.append(entry)

d = { i : l[i] for i in range(0, len(l) ) }

print json.dumps(d)
