version: '3'
services:
  app:
    build: ./app
    volumes:
        - /var/run/docker.sock/:/var/run/docker.sock
        - ./app/log:/app/log
    ports:
        - 8080:8000
#    links:
#        - db:db
    depends_on:
        - db
        - livivo_rank_precom
        - livivo_rank_pyserini
        - gesis_rec_precom
        - gesis_rec_pyserini
    environment:
        - RANKSYS_LIST=livivo_rank_pyserini
        - RECSYS_LIST=gesis_rec_pyserini
        - RANKSYS_PRECOM_LIST=livivo_rank_precom
        - RECSYS_PRECOM_LIST=gesis_rec_precom
        - RANKSYS_BASE=livivo_rank_pyserini
        - RECSYS_BASE=gesis_rec_pyserini
        - STELLA_SERVER_ADDRESS=http://web:8000
        - STELLA_SERVER_USER=livivo@stella-project.org
        - STELLA_SERVER_PASS=pass
        - STELLA_SERVER_USERNAME=LIVIVO
        - INTERLEAVE=True
        - BULK_INDEX=True
        - DELETE_SENT_SESSION=False
        - INTERVAL_DB_CHECK=3
        - SESSION_EXPIRATION=240
  db:
    image: postgres
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres

  livivo_rank_precom:
    build: https://github.com/stella-project/livivo_rank_precom.git#master
    container_name: livivo_rank_precom
    volumes:
        - ./data/:/data/
  livivo_rank_pyserini:
    build: https://github.com/stella-project/livivo_rank_pyserini.git#master
    container_name: livivo_rank_pyserini
    volumes:
        - ./data/:/data/
  gesis_rec_precom:
    build: https://github.com/stella-project/gesis_rec_precom.git#master
    container_name: gesis_rec_precom
    volumes:
        - ./data/:/data/
  gesis_rec_pyserini:
    build: https://github.com/stella-project/gesis_rec_pyserini.git#master
    container_name: gesis_rec_pyserini
    volumes:
        - ./data/:/data/
  web:
    restart: always
    build: https://github.com/stella-project/stella-server.git#:web
    ports:
      - 8000:8000
    command: bash -c "python stella-server.py"
    environment:
      - FLASK_CONFIG=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PW=postgres
      - POSTGRES_DB=postgres
      - SECRET_KEY=change-me
      - AUTOMATOR_GH_KEY=
      - ADMIN_MAIL=admin@stella-project.org
      - ADMIN_PASS=pass
      - GESIS_MAIL=gesis@stella-project.org
      - GESIS_PASS=pass
      - LIVIVO_MAIL=livivo@stella-project.org
      - LIVIVO_PASS=pass
      - PARTA_MAIL=participant_a@stella-project.org
      - PARTA_PASS=pass
      - PARTB_MAIL=participant_b@stella-project.org
      - PARTB_PASS=pass
#    links:
#      - db_server:db_server
    depends_on:
      - db_server
  db_server:
    image: postgres
    expose:
      - 5430
    ports:
      - 5430:5430
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    command: -p 5430
