version: '3'
services:
    web:
      build: ./app
      volumes:
        - /var/run/docker.sock/:/var/run/docker.sock
        - ./app/log:/app/log
      ports:
        - "80:80"
      depends_on:
        - elastic
        - recomm-sample
        - recomm_new
    elastic:
        build: ./elastic
        container_name: elastic
        volumes:
          - ./data/:/data/


    recomm-sample:
        build: ./recomm-sample
        container_name: recomm-sample
        ports:
        - "8889:8889"        
        volumes:
          - ./data:/data
        tty: true

    recomm_new:
        build: ./recomm_new
        container_name: recomm_new
        ports:
        - "8888:8888"          
        volumes:
          - ./data:/data
        tty: true
