name: stella-dev

networks:
  stella-shared:
    external: true
    name: stella-shared

services:
  app:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./data:/data
      - ./web:/app
    expose:
      - "8000"
    ports:
      - "8080:8000"
    networks:
      stella-shared:
        aliases:
          - stella-app
    environment:
      # Config
      FLASK_APP: app/app
      DEBUG: "True"
      FLASK_CONFIG: postgres
      INTERLEAVE: "True"
      BULK_INDEX: "False"
      INTERVAL_DB_CHECK: 3
      SESSION_EXPIRATION: 6
      SESSION_KILL: 120
      SEND_FEEDBACK: "False"

      # Systems
      SYSTEMS_CONFIG: |
        {
            "gesis_rec_pyterrier": {"type": "recommender", "base": true},
            "gesis_rec_pyserini": {"type": "recommender"},
            "gesis_rank_pyserini_base": {"type": "ranker", "base": true},
            "gesis_rank_pyserini": {"type": "ranker"}
        }
      # Stella Server
      STELLA_SERVER_ADDRESS: http://stella-server:8000
      STELLA_SERVER_USER: site@stella-project.org
      STELLA_SERVER_PASS: pass
      STELLA_SERVER_USERNAME: site

      # Database
      POSTGRES_USER: postgres
      POSTGRES_PW: change-me
      POSTGRES_DB: postgres
      POSTGRES_URL: db-app:5430

    command: flask run --host=0.0.0.0 --port=8000 --reload --debug
    depends_on:
      - db-app
      - gesis_rec_pyterrier
      - gesis_rec_pyserini
      - gesis_rank_pyserini_base
      - gesis_rank_pyserini

  db-app:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db-app-data:/var/lib/postgresql/data
    expose:
      - "5430"
    ports:
      - "5430:5430"
    networks:
      - stella-shared
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=change-me
      - POSTGRES_DB=postgres
    command: -p 5430

  gesis_rank_pyserini_base:
    build: https://github.com/stella-project/gesis_rank_pyserini_base.git#main
    container_name: gesis_rank_pyserini_base
    volumes:
      - ./data/:/data/
    networks:
      - stella-shared

  gesis_rank_pyserini:
    build: https://github.com/stella-project/gesis_rank_pyserini.git#main
    container_name: gesis_rank_pyserini
    volumes:
      - ./data/:/data/
    networks:
      - stella-shared

  gesis_rec_pyterrier:
    build: https://github.com/stella-project/gesis_rec_pyterrier.git#master
    container_name: gesis_rec_pyterrier
    volumes:
      - ./data/:/data/
    networks:
      - stella-shared

  gesis_rec_pyserini:
    build: https://github.com/stella-project/gesis_rec_pyserini.git#master
    container_name: gesis_rec_pyserini
    volumes:
      - ./data/:/data/
    networks:
      - stella-shared
