version: '3'
services:
  app:
    build: ./app
    volumes:
        - /var/run/docker.sock/:/var/run/docker.sock
        - ./app/log:/app/log
    ports:
        - 8080:8000
    links:
        - db:db
    depends_on:
        - db
        - livivo_base
        - livivo_rank_precom
        - livivo_rank_pyserini
        - livivo_rank_pyterrier
    environment:
        - RANKSYS_LIST=livivo_base livivo_rank_pyserini livivo_rank_pyterrier
        - RANKSYS_PRECOM_LIST=livivo_rank_precom
        - RANKSYS_BASE=livivo_base
        - STELLA_SERVER_ADDRESS=https://lilas.stella-project.org
        - STELLA_SERVER_USER=livivo@stella-project.org
        - STELLA_SERVER_PASS=pass
        - STELLA_SERVER_USERNAME=LIVIVO
        - INTERLEAVE=True
        - BULK_INDEX=True
        - DELETE_SENT_SESSION=True
        - INTERVAL_DB_CHECK=3
        - SESSION_EXPIRATION=6
  db:
    image: postgres
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
  livivo_base:
    build: https://github.com/stella-project/livivo_rank_base.git
    container_name: livivo_base
    volumes:
        - ./data/:/data/
  livivo_rank_precom:
    build: https://github.com/stella-project/livivo_rank_precom.git
    container_name: livivo_rank_precom
    volumes:
        - ./data/:/data/
  livivo_rank_pyserini:
    build: https://github.com/stella-project/livivo_rank_pyserini.git
    container_name: livivo_rank_pyserini
    volumes:
        - ./data/:/data/
  livivo_rank_pyterrier:
    build: https://github.com/stella-project/livivo_rank_pyterrier.git
    container_name: livivo_rank_pyterrier
    volumes:
        - ./data/:/data/
