version: '3'
services:
  app:
    build: ./app
    volumes:
        - /var/run/docker.sock/:/var/run/docker.sock
        - ./app/log:/app/log
    ports:
        - 8080:8000
    links:
        - db:db
    depends_on:
        - db
        - livivo_base
        - livivo_rank_pyserini
        - lemuren_elastic_only
        - lemuren_elastic_preprocessing
    environment:
        - RANKSYS_LIST=livivo_base livivo_rank_pyserini lemuren_elastic_only lemuren_elastic_preprocessing
        - RANKSYS_BASE=livivo_base
        - STELLA_SERVER_ADDRESS=https://lilas.stella-project.org
        - STELLA_SERVER_USER=gesis@stella-project.org
        - STELLA_SERVER_PASS=pass
        - STELLA_SERVER_USERNAME=GESIS
        - INTERLEAVE=True
        - BULK_INDEX=True
        - DELETE_SENT_SESSION=True
        - INTERVAL_DB_CHECK=3
        - SESSION_EXPIRATION=6
  db:
    image: postgres
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
  livivo_base:
    build: https://github.com/stella-project/livivo_rank_base.git#main
    container_name: livivo_base
    volumes:
        - ./data/:/data/
        - ./index/livivo_base:/index/
  livivo_rank_pyserini:
    build: https://github.com/stella-project/livivo_rank_pyserini.git#master
    container_name: livivo_rank_pyserini
    volumes:
        - ./data/:/data/
        - ./index/livivo_rank_pyserini:/index/
  lemuren_elastic_only:
    build: https://github.com/dis22-lilas/lemuren_elastic_only.git#main
    container_name: lemuren_elastic_only
    volumes:
        - ./data/:/data/
        - ./index/lemuren_elastic_only:/index/
  lemuren_elastic_preprocessing:
    build: https://github.com/dis22-lilas/elastic_lemuren_preprocessing.git#main
    container_name: lemuren_elastic_preprocessing
    volumes:
        - ./data/:/data/
        - ./index/lemuren_elastic_preprocessing:/index/
