version: '3'
services:
    app:
        build: ./app
        volumes:
          - /var/run/docker.sock/:/var/run/docker.sock
          - ./app/log:/app/log
        ports:
            - "8080:8000"
        depends_on:
            - rank_elastic
            - rank_elastic_base
            - recom_tfidf
            - recom_tfidf_base

    rank_elastic:
        build: ./rank_elastic
        container_name: rank_elastic
        volumes:
          - ./data/:/data/

    rank_elastic_base:
        build: ./rank_elastic_base
        container_name: rank_elastic_base
        volumes:
          - ./data/:/data/

    recom_tfidf:
        build: ./recom_tfidf
        container_name: recom_tfidf
        volumes:
          - ./data/:/data/

    recom_tfidf_base:
        build: ./recom_tfidf
        container_name: recom_tfidf_base
        volumes:
          - ./data/:/data/
