version: '3'

networks:
    stella-shared:
        external:
            name: stella-server_default

services:
    app:
        build: ./app
        volumes:
          - /var/run/docker.sock/:/var/run/docker.sock
          - ./app/log:/app/log
        ports:
            - "8080:8000"
        depends_on:
            - livivo_elastic
            - livivo_elastic_base
            - recom_tfidf
        networks:
            - stella-shared

    livivo_elastic:
        build: ./livivo_elastic
        container_name: livivo_elastic
        volumes:
          - ./livivo_elastic/data/:/data/
        networks:
            - stella-shared

    livivo_elastic_base:
        build: ./livivo_elastic_base
        container_name: livivo_elastic_base
        volumes:
          - ./livivo_elastic/data/:/data/
        networks:
            - stella-shared
          
    recom_tfidf:
        build: ./recom_tfidf
        container_name: recom_tfidf
        volumes:
          - ./data:/data
        networks:
            - stella-shared
