version: '3'
services:
  app:
    build: ./app
    volumes:
        - /var/run/docker.sock/:/var/run/docker.sock
        - ./app/log:/app/log
    ports:
        - 8080:8000
    depends_on:
        - livivo_base
        - livivo_rank_precom
        - livivo_rank_pyserini
        - livivo_rank_pyterrier
    environment:
        - RANKSYS_LIST=livivo_base livivo_rank_pyserini livivo_rank_pyterrier
        - RANKSYS_PRECOM_LIST=livivo_rank_precom
        - RANKSYS_BASE=livivo_base
        - STELLA_SERVER_ADDRESS=nginx
        - STELLA_SERVER_USER=gesis@stella.org
        - STELLA_SERVER_PASS=pass
        - STELLA_SERVER_USERNAME=GESIS
        - INTERLEAVE=True
        - BULK_INDEX=True
        - DELETE_SENT_SESSION=True
        - INTERVAL_DB_CHECK=3
        - SESSION_EXPIRATION=6
  livivo_base:
    build: https://github.com/stella-project/livivo_rank_base.git#main
    container_name: livivo_base
    volumes:
        - ./data/:/data/
  livivo_rank_precom:
    build: https://github.com/stella-project/livivo_rank_precom.git#master
    container_name: livivo_rank_precom
    volumes:
        - ./data/:/data/
  livivo_rank_pyserini:
    build: https://github.com/stella-project/livivo_rank_pyserini.git#master
    container_name: livivo_rank_pyserini
    volumes:
        - ./data/:/data/
  livivo_rank_pyterrier:
    build: https://github.com/stella-project/livivo_rank_pyterrier.git#master
    container_name: livivo_rank_pyterrier
    volumes:
        - ./data/:/data/
