#!/usr/bin/env python2.7

from subprocess import Popen, PIPE
import json
import os
import sys

query = sys.argv[1]

CMD = "curl http://solr:8983/solr/collection/select?q=" + query

p = Popen(CMD.split(), stdout=PIPE, stderr=PIPE)
output, err = p.communicate()
rc = p.returncode

l = []

for entry in json.loads(output)['response']['docs']:
    l.append(os.path.basename(entry['id']))

d = { i : l[i] for i in range(0, len(l) ) }

print json.dumps(d)
