#!/usr/bin/env python3

from elasticsearch import Elasticsearch
import json
import os

PATH = '/data/'

es = Elasticsearch([{'host': 'localhost',
                     'port': 9200}])

for file in os.listdir(PATH):
    if file.endswith(".json"):
        with open(os.path.join(PATH, file), 'r', encoding="utf-8") as f:
            for line in f:
                doc = json.loads(line)

                es.index(index=doc['source'],
                         doc_type=doc['type'],
                         id=doc['id'],
                         body=doc)
