#!/usr/bin/env python3

from elasticsearch import Elasticsearch
import json
import os
import ast

PATH = '/data/'
#PATH = '/home/tavakons/hackaton/stella-app/data/'

es = Elasticsearch([{'host': 'localhost',
                     'port': 9200}])

for file in os.listdir(PATH):
    if file.endswith("ALL.json"):
        with open(os.path.join(PATH, file), 'r', encoding="utf-8") as f:
            for line in f:
                #doc = json.loads(f)
                try:
                   doc = ast.literal_eval(line)
                   es.index(index=doc['type'], doc_type=doc['type'],id=doc['id'],body=doc)
                except:
                   #print(doc['id'])
                   pass
