#!/usr/bin/env python3

from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import json
import os
import sys

query = sys.argv[1]

es = Elasticsearch([{'host': 'localhost', 'port': 9200}])

result = es.search(index="publication", size= "1000", body={"query": {"match": {"title": query}}})

output = {}
cnt = 0


for res in result["hits"]["hits"]:
    hit = res['_source']
    out = {}
    out['id'] = hit.get('id')
    out['title'] = hit.get('title')
    out['article_url'] = hit.get('links')
    out['type'] = hit.get('type')
    out['text'] = hit.get('abstract')
    out['author'] = hit.get('person')
    out['source'] = hit.get('data_source')
    out['published_date'] = hit.get('date')
    output[cnt] = out
    cnt += 1

print(json.dumps(output))
