#!/usr/bin/env python3

from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import json
import os
import sys

query = sys.argv[1]

es = Elasticsearch([{'host': 'localhost',
                     'port': 9200}])

s = Search().using(es).query("match", text=query)
s.execute()

output = {}
cnt = 0
for hit in s:
    out = {}
    out['id'] = hit.id
    out['title'] = hit.title
    out['article_url'] = hit.article_url
    out['type'] = hit.type
    out['text'] = hit.text
    out['author'] = hit.author
    out['source'] = hit.source
    out['published_date'] = hit.published_date
    output[cnt] = out
    cnt += 1

print(json.dumps(output))


# import json
# import os
# import sys

# from elasticsearch import Elasticsearch
# from elasticsearch_dsl import Search

# query = sys.argv[1]


# es = Elasticsearch([{'host': 'localhost',
#                      'port': 9200}])

# s = Search().using(es).query("match", text=query)
# s.execute()

# count = 0

# d = {}

# for hit in s:
#     d[count] = hit.meta.id
#     count+=1

# print(json.dumps(d))