version: '3'
services:
  app:
    build: ../app
    volumes:
        - /var/run/docker.sock/:/var/run/docker.sock
        - ../app/log:/app/log
    ports:
        - 8080:8000
    depends_on:
        - db
        - gesis_rank_precom_base
        - gesis_rank_precom
        - gesis_rank_pyserini_base
        - gesis_rank_pyserini
        - gesis_rec_precom
        - gesis_rec_pyserini

    environment:
        - RANKSYS_LIST=gesis_rank_pyserini gesis_rank_pyserini_base
        - RECSYS_LIST=gesis_rec_pyserini gesis_rec_pyserini
        - RANKSYS_PRECOM_LIST=gesis_rank_precom
        - RECSYS_PRECOM_LIST=gesis_rec_precom
        - RANKSYS_BASE=gesis_rank_pyserini_base
        - RECSYS_BASE=gesis_rec_pyserini
        - STELLA_SERVER_ADDRESS=http://web:8000
        - STELLA_SERVER_USER=gesis@stella-project.org
        - STELLA_SERVER_PASS=pass
        - STELLA_SERVER_USERNAME=GESIS
        - INTERLEAVE=True
        - BULK_INDEX=True
        - DELETE_SENT_SESSION=False
        - INTERVAL_DB_CHECK=3
        - SESSION_EXPIRATION=240
  db:
    image: postgres
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres

  gesis_rank_precom_base:
    build: https://github.com/stella-project/gesis_rank_precom_base.git#main
    container_name: gesis_rank_precom_base
    volumes:
        - ../data/:/data/
        - ../index/gesis_rank_precom_base:/index/
  gesis_rank_precom:
    build: https://github.com/stella-project/gesis_rank_precom.git#main
    container_name: gesis_rank_precom
    volumes:
        - ../data/:/data/
        - ../index/gesis_rank_precom:/index/
  gesis_rank_pyserini:
    build: https://github.com/stella-project/gesis_rank_pyserini.git#main
    container_name: gesis_rank_pyserini
    volumes:
        - ../data/:/data/
        - ../index/gesis_rank_pyserini:/index/
  gesis_rank_pyserini_base:
    build: https://github.com/stella-project/gesis_rank_pyserini_base.git#main
    container_name: gesis_rank_pyserini_base
    volumes:
      - ../data/:/data/
      - ../index/gesis_rank_pyserini_base:/index/
  gesis_rec_precom:
    build: https://github.com/stella-project/gesis_rec_precom.git#master
    container_name: gesis_rec_precom
    volumes:
        - ../data/:/data/
        - ../index/gesis_rec_precom:/index/
  gesis_rec_pyserini:
    build: https://github.com/stella-project/gesis_rec_pyserini.git#master
    container_name: gesis_rec_pyserini
    volumes:
      - ../data/:/data/
      - ../index/gesis_rec_pyserini:/index/
  web:
    restart: always
    build: https://github.com/stella-project/stella-server.git#:web
    ports:
      - 8000:8000
    command: bash -c "python stella-server.py"
    environment:
      - FLASK_CONFIG=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PW=postgres
      - POSTGRES_DB=postgres
      - SECRET_KEY=change-me
      - AUTOMATOR_GH_KEY=
      - ADMIN_MAIL=admin@stella-project.org
      - ADMIN_PASS=pass
      - GESIS_MAIL=gesis@stella-project.org
      - GESIS_PASS=pass
      - LIVIVO_MAIL=livivo@stella-project.org
      - LIVIVO_PASS=pass
      - PARTA_MAIL=participant_a@stella-project.org
      - PARTA_PASS=pass
      - PARTB_MAIL=participant_b@stella-project.org
      - PARTB_PASS=pass
    depends_on:
      - db_server
  db_server:
    image: postgres
    expose:
      - 5430
    ports:
      - 5430:5430
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    command: -p 5430