apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db-app
  name: db-app
spec:
  ports:
    - name: "5430"
      port: 5430
      targetPort: 5430
  selector:
    io.kompose.service: db-app