apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: stella-app
  name: stella-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stella-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: stella-app
    spec:
      containers:
        - args:
            - gunicorn
            - -w
            - "2"
            - --timeout
            - "60"
            - -b
            - :8000
            - app.app:create_app()
          env:
            - name: BULK_INDEX
              value: "False"
            - name: DELETE_SENT_SESSION
              value: "True"
            - name: FLASK_APP
              value: app/app
            - name: FLASK_CONFIG
              value: postgres
            - name: INTERLEAVE
              value: "True"
            - name: INTERVAL_DB_CHECK
              value: "3"
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PW
              value: change-me
            - name: POSTGRES_URL
              value: db-app:5430
            - name: POSTGRES_USER
              value: postgres
            - name: SESSION_EXPIRATION
              value: "6"
            - name: STELLA_SERVER_ADDRESS
              value: http://stella-server:8000
            - name: STELLA_SERVER_PASS
              value: pass
            - name: STELLA_SERVER_USER
              value: site@stella-project.org
            - name: STELLA_SERVER_USERNAME
              value: site
            - name: SYSTEMS_CONFIG
              value: |
                {
                    "gesis_rec_pyterrier": {"type": "recommender", "base": true},
                    "gesis_rec_pyserini": {"type": "recommender"},
                    "gesis_rank_pyserini_base": {"type": "ranker", "base": true},
                    "gesis_rank_pyserini": {"type": "ranker"}
                }
          image: docker.io/dnztrkmn/stella-app:latest
          name: stella-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always